//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableColorModel
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int ColorId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
    }
}
