//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckingAccount
    {
        public int Id { get; set; }
        public Nullable<int> StockRoomId { get; set; }
        public Nullable<int> StoreStockRoomId { get; set; }
        public Nullable<double> Charge { get; set; }
        public Nullable<double> Incoming { get; set; }
        public Nullable<int> SaleId { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual StoreStockRoom StoreStockRoom { get; set; }
        public virtual StockRoom StockRoom { get; set; }
    }
}
