//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.SaleProducts = new HashSet<SaleProduct>();
            this.StoreStockRooms = new HashSet<StoreStockRoom>();
            this.StockRooms = new HashSet<StockRoom>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int ColorId { get; set; }
        public double Size { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<SaleProduct> SaleProducts { get; set; }
        public virtual ICollection<StoreStockRoom> StoreStockRooms { get; set; }
        public virtual ICollection<StockRoom> StockRooms { get; set; }
    }
}
