//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sales = new HashSet<Sale>();
            this.StoreSupplies = new HashSet<StoreSupply>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int ColorId { get; set; }
        public double Size { get; set; }
        public int Quantity { get; set; }
        public double UnitCost { get; set; }
        public System.DateTime InputDate { get; set; }
        public string Description { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<StoreSupply> StoreSupplies { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
