//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoesDBEntities : DbContext
    {
        public ShoesDBEntities()
            : base("name=ShoesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<SaleProduct> SaleProducts { get; set; }
        public DbSet<Seller> Sellers { get; set; }
        public DbSet<StockRoom> StockRooms { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreStockRoom> StoreStockRooms { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<ShoesType> ShoesTypes { get; set; }
        public DbSet<ModelColor> ModelColors { get; set; }
    }
}
