//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systems.Appollo.Shoes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Sales = new HashSet<Sale>();
            this.StoreStockRooms = new HashSet<StoreStockRoom>();
            this.StockRooms = new HashSet<StockRoom>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int SellerId { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual ICollection<StoreStockRoom> StoreStockRooms { get; set; }
        public virtual ICollection<StockRoom> StockRooms { get; set; }
    }
}
